### ISSUE TITLE
peer-to-peer review

### ISSUE THREAD

**Issue by suzi216** [Suzi216/trial-review#2]
### **This is a review from all my team partners.**

**Comment by suzi216** [comment]
**TO DO**

- In the code, the li tag should not be left out of ul tag. Together they form an unordered list.
- The header tag should not be placed at the end of html. It is usually placed at the beginning of the page.
- You do not need to add a class and id at the same time. One of them would do the work.

**Comment by Therealadetunji** [comment]
alot of lists are inputed without specifying if it's ordered or un-ordered

**Comment by ChaabaneAnas** [comment]
## CHANGES REQUIRED :pen:  :pen: 

**Good job so far Suzi216, You've done a good job so far
     but there are some changes I would like to suggest**


- kindly edit your Readme file to match the Microverse readme file or simply download it from [here](https://github.com/microverseinc/readme-templaterl),
this will make your work look professional and well structured.

- Please add a viewport element to your head tag, otherwise it will cause you problems with your webhint linter,
and even leads to more bugs.

- Now that you learned CSS Grid and flexbox structuring your webpage should be a piece of cake,
try making use of them for a more structured Page.
